### ISSUE TITLE
Non random quilt w. abilty to choose views size dynamically w. out gaps

### ISSUE THREAD

**Issue by fresh83** [jacobmoncur/QuiltViewLibrary#6]

**Comment by jacobmoncur** [comment]
Pull down the latest commit to master. It has a more structured approach to building the quilt so that there are no gaps.

**Comment by fresh83** [comment]
Ill check it out. Thank you much sir!

**Comment by fresh83** [comment]
@jacobmoncur would you mind having a private email convo with me regarding this lib ?  If you dont feel comfortable sharing your email mine is fresh83@live.com . I realize your probably pretty busy and this is a open source project so Id be more than willing to pay your for your time via paypal for consulting me on how i could modify your lib for the desired effect im looking to achieve.
